# Generated by Django 5.2.13 on 2026-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="client_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("held", "Held"),
                    ("booked", "Booked"),
                    ("walk_in", "Walk-in"),
                ],
                default="available",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="WalkIn",
        ),
    ]
